---
abstract: 'Perl extension for blah blah blah'
author:
  - 'Pomin Wu <pm5@nonet>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.141170'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Lorem-Moretext
no_index:
  directory:
    - t
    - inc
requires: {}
version: '0.01'
